config/routes.rb
Rails.application.routes.draw do
  
  root'lists#index'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  resources :users

  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :email, :password
	validates_uniqueness_of :email
	validates_presence_of :password_confirmation, on: :create
	validates_confirmation_of :password

	has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

	def authenticate_user!
		unless current_user
			redirect_to signin_path, notice: "You must log in to do that."
		end
	end
	
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index

    if current_user 
    	@lists = current_user.lists.all.reverse
    else
      redirect_to signin_path
    end
  end

  def create
    @list = List.create(list_params)

    if @list.save

      respond_to do |format|
        format.html {redirect_to root_path, notice: 'New item added!' }
        format.js {flash.now[:notice] = "New List Item!"}
      end

    else 

      respond_to do |format|
        format.html {redirect_to root_path, notice: "Something just ain't right"}
        format.js {flash.now[:notice] = "There was a problem, homie"}
      end

    end

  end


  def edit
    @list = List.find(params[:id])
  end

  def update
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js   { render :layout => false }
    end

  end

  private

  def list_params
  	params.require(:list).permit(:title).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.id
  		redirect_to root_path, notice: "Signed in."
  	else
  		redirect_to signin_path, notice: "There was a problem sigining in."
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params_user)
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to root_path, notice: "New account created."
  	else
      redirect_to root_path, notice: "There was a problem, homie. Looks like you ain't doin' nothin' today."
  	end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Account was deleted."
  end

  private

  def params_user
  	params.require(:user).permit(:username, :email, :password, :password_confirmation, :about)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UncubedChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<nav>
		<% if current_user %>
			<%= link_to 'sign out', signout_path, method: :delete, class: "signout" %>
		<% else %>
			<%= link_to 'sign in', signin_path, class: "signin" %>
			<%= link_to 'sign up', new_user_path, class: "signup" %>
		<% end %>
	</nav>
</header>
<main>
	
	<%= yield %>
</main>
</body>
</html>

app/views/lists/_list.html.erb
<div id="list-item" data-list-id="<%= list.id %>">

	<form class="list-item-crossOff">
		<input type="checkbox" id="list-item-checkbox">
	</form>

	<h3 class="list-item-title"><%= list.title %></h3>

	<p class="list-item-created-at">Created at <%= list.created_at.strftime("%d %b. %Y") %></p>

	<%= link_to "Remove", list_path(list.id), method: :delete, remote: true, class: "delete-item" %> 

</div>

app/views/lists/create.js.erb
$('.list-item-container').prepend("<%= j render @list %>");
$('.list-item-title-input').val('');
$('.list-item-crossOff :checkbox').click(function() {
    
  var $this = $(this);

 	var todoTitle = $this.parent().siblings("h3");

  if ($this.is(':checked')) {

    todoTitle.css("text-decoration", "line-through");


  } else {

    todoTitle.css("text-decoration", "none");


  }

});

app/views/lists/destroy.js.erb
$('.delete-item').bind('ajax:success', function() {  
  $(this).closest('div').fadeOut(700);
});  

app/views/lists/edit.html.erb
<%= render 'shared/list_update' %>

app/views/lists/index.html.erb
<% if current_user %>

  <h1>Welcome <%= current_user.username %>. Here's what you gotta do today</h1>

	<%= render 'shared/list_form' %>

  <h3><%=current_user.username%>'s things to do:</h3>

  <div class="list-item-container">
  	<%= render @lists %>
  </div>


<% end %> 

app/views/shared/_list_form.html.erb
<div class="list-form">
	<%= form_for List.new, remote: true, class: "list-item-form" do |f| %>
		

		<%= f.label :title, "Be productive.", class: "list-item-title-label" %><br>
		<%= f.text_field :title, class: "list-item-title-input" %>


		<%= f.submit 'add to list', class: "list-form-submit" %>


	<% end %> 

</div>

app/views/shared/_list_update.html.erb
<div>
	<%= form_for @list, remote: true, class: "list-item-form" do |f| %>
		
		<p>
			<%= f.label :title %>
			<%= f.text_field :title, class: "list-item-title" %>
		</p>
		<p>
			<%= f.label :description %>
			<%= f.text_field :description, class: "list-item-description" %>
		</p>
		<p>
		  <%= f.label :progress %>
		  <%= f.number_field :progress, class: "list-item-progress" %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %> 

</div>

app/views/shared/_new_user.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="alert">
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</div>
	<% end %>
	
	<p>
		<%= f.label :username, "Username" %>
		<%= f.text_field :username, required: true, placeholder: "Username" %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email, required: true, placeholder: "Email" %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password, required: true, placeholder: "Password" %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, required: true, placeholder: "Password" %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/shared/_sign_in.html.erb
<%= form_tag '/signin' do %>
	<p>
		<%= label_tag :email %>
		<%= email_field_tag :email %>
	</p>
	<p>
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</p>
	<p>
		<%= submit_tag "Log in" %>
	</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up, or never accomplish anything. Ever.</h1>

<%= render 'shared/new_user' %>